{{- if .Values.global.certManagerEnabled}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: drycc-auto-tls
spec:
  dnsNames:
  {{- range $app := .Values.apps }}
  {{- if $app.hostname }}
  - {{ tpl $app.hostname $ }}
  {{- end }}
  {{- end }}
  issuerRef:
    kind: Issuer
    name: drycc-issuer
  privateKey:
    rotationPolicy: Always
  secretName: drycc-auto-tls
{{- end }}
