apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: drycc-gateway
  {{- if .Values.global.certManagerEnabled}}
  annotations:
    cert-manager.io/issuer: drycc-issuer
  {{- end }}
spec:
  gatewayClassName: {{ .Values.global.gatewayClass }}
  listeners:
  {{- range $index, $app := .Values.apps }}
  - name: {{ printf "%s-%v-%d" $app.protocol $app.port $index | lower }}
    port: {{ $app.port }}
    {{- if $app.hostname }}
    hostname: {{ tpl $app.hostname $ }}
    {{- end }}
    protocol: {{ $app.protocol }}
    allowedRoutes:
      namespaces:
        from: All
  {{- if and (eq $app.protocol "HTTP") ($.Values.global.certManagerEnabled) }}
  - name: {{ printf "%s-%v-%d" "https" $app.port $index | lower }}
    port: 443
    {{- if $app.hostname }}
    hostname: {{ tpl $app.hostname $ }}
    {{- end }}
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: drycc-auto-tls
      mode: Terminate
    allowedRoutes:
      namespaces:
        from: All
  {{- end }}
  {{- end }}
