apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: drycc-gateway
spec:
  gatewayClassName: {{ .Values.global.gatewayClass }}
  listeners:
  - name: drycc-gateway-listener-http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  {{- if .Values.global.certManagerEnabled}}
  - name: drycc-gateway-listener-https
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: drycc-auto-tls
      mode: Terminate
    allowedRoutes:
      namespaces:
        from: All
  {{- end }}
  {{- with .Values.customListeners }}{{- toYaml . | nindent 2 }}{{- end }}
