# acme configuration takes effect if and only if certManagerEnabled is true
acme:
  server: https://acme-v02.api.letsencrypt.org/directory
  #  EAB credentials
  externalAccountBinding:
    keyID: ""
    keySecret: ""
# gateway apps
apps:
  - name: drycc-builder
    port: 2222
    protocol: TCP
    services:
    - name: drycc-builder
      port: 2222
  - name: drycc-controller
    port: 80
    hostname: drycc.{{ .Values.global.platformDomain }}
    protocol: HTTP
    services:
    - name: drycc-controller-api
      port: 80
  - name: drycc-rabbitmq
    port: 80
    hostname: drycc-rabbitmq.{{ .Values.global.platformDomain }}
    protocol: HTTP
    services:
    - name: drycc-rabbitmq
      port: 15672
  - name: drycc-passport
    port: 80
    hostname: drycc-passport.{{ .Values.global.platformDomain }}
    protocol: HTTP
    services:
    - name: drycc-passport
      port: 80
  - name: drycc-prometheus
    port: 80
    hostname: drycc-prometheus.{{ .Values.global.platformDomain }}
    protocol: HTTP
    services:
    - name: drycc-prometheus
      port: 9090
  - name: drycc-monitor-grafana
    port: 80
    hostname: drycc-monitor-grafana.{{ .Values.global.platformDomain }}
    protocol: HTTP
    services:
    - name: drycc-monitor-grafana
      port: 80

global:
  # Admin email, used for each component to send email to administrator
  email: "drycc@drycc.cc"
  gatewayClass: ""
  # The publicly resolvable hostname to build your cluster with.
  #
  # This will be the hostname that is used to build endpoints such as "drycc.$HOSTNAME"
  platformDomain: ""
  # Whether certManagerEnabled is true to automatically generate drycc certificates
  certManagerEnabled: false
